-- ==============================================================================
-- Schema Migration: Relational team and team_seasons tables
-- ==============================================================================

-- 1. Ensure public.team has all permanent identity fields
CREATE TABLE IF NOT EXISTS public.team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  avatar_img TEXT,
  normal_img TEXT,
  birthday DATE,
  department TEXT,
  social_media_links JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- In case public.team already exists, make sure columns exist
ALTER TABLE public.team ADD COLUMN IF NOT EXISTS birthday DATE;
ALTER TABLE public.team ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE public.team ADD COLUMN IF NOT EXISTS avatar_img TEXT;
ALTER TABLE public.team ADD COLUMN IF NOT EXISTS normal_img TEXT;
ALTER TABLE public.team ADD COLUMN IF NOT EXISTS social_media_links JSONB DEFAULT '{}'::jsonb;

-- 2. Create public.team_seasons table
CREATE TABLE IF NOT EXISTS public.team_seasons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES public.team(id) ON DELETE CASCADE,
  season TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'Team Member',
  post_abbr TEXT,
  post_order INT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_member_season UNIQUE (team_id, season)
);

-- 3. Indexes for fast join, season filtering, and order sorting
CREATE INDEX IF NOT EXISTS idx_team_seasons_team_id ON public.team_seasons(team_id);
CREATE INDEX IF NOT EXISTS idx_team_seasons_season_order ON public.team_seasons(season, post_order ASC NULLS LAST);

-- 4. Enable Row Level Security (RLS) & standard public read access
ALTER TABLE public.team ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_seasons ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'team' AND policyname = 'Public read team'
  ) THEN
    CREATE POLICY "Public read team" ON public.team FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'team' AND policyname = 'Allow all team modifications'
  ) THEN
    CREATE POLICY "Allow all team modifications" ON public.team FOR ALL USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'team_seasons' AND policyname = 'Public read team_seasons'
  ) THEN
    CREATE POLICY "Public read team_seasons" ON public.team_seasons FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'team_seasons' AND policyname = 'Allow all team_seasons modifications'
  ) THEN
    CREATE POLICY "Allow all team_seasons modifications" ON public.team_seasons FOR ALL USING (true);
  END IF;
END $$;
