-- ==============================================================================
-- Schema Migration: Robotics & AI Club Registration & Membership System
-- ==============================================================================

-- 1. Table: registration_settings
-- Controls whether registration is open and the active season
CREATE TABLE IF NOT EXISTS public.registration_settings (
  id SERIAL PRIMARY KEY,
  is_open BOOLEAN NOT NULL DEFAULT true,
  active_season TEXT NOT NULL DEFAULT '2025-2026',
  closed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial settings row if not present
INSERT INTO public.registration_settings (id, is_open, active_season)
VALUES (1, true, '2025-2026')
ON CONFLICT (id) DO UPDATE SET
  is_open = EXCLUDED.is_open,
  active_season = EXCLUDED.active_season;

-- 2. Table: registrations (Temporary registration applications)
CREATE TABLE IF NOT EXISTS public.registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  department TEXT NOT NULL,
  filiere TEXT NOT NULL,
  years_of_study TEXT NOT NULL,
  message TEXT,
  registration_season TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  refusal_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT check_reg_status CHECK (status IN ('pending', 'accepted', 'refused')),
  CONSTRAINT registrations_refusal_reason_check CHECK (
    (status = 'refused' AND length(trim(refusal_reason)) BETWEEN 1 AND 2000)
    OR (status IN ('pending', 'accepted') AND refusal_reason IS NULL)
  ),
  CONSTRAINT check_reg_years CHECK (years_of_study IN ('first_year', 'second_year', 'bachelor', 'master', 'phd'))
);

CREATE INDEX IF NOT EXISTS idx_registrations_season_status ON public.registrations(registration_season, status);

-- 3. Table: members (Permanent regular club members — completely separate from team/staff)
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  department TEXT NOT NULL,
  filiere TEXT NOT NULL,
  years_of_study TEXT NOT NULL,
  message TEXT,
  registration_season TEXT NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT check_mem_years CHECK (years_of_study IN ('first_year', 'second_year', 'bachelor', 'master', 'phd'))
);

CREATE INDEX IF NOT EXISTS idx_members_season ON public.members(registration_season);

-- 4. Table: refused_members (Permanently stored refused applications)
CREATE TABLE IF NOT EXISTS public.refused_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_registration_id BIGINT,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  department TEXT NOT NULL,
  filiere TEXT NOT NULL,
  years_of_study TEXT NOT NULL,
  message TEXT,
  registration_season TEXT NOT NULL,
  refusal_reason TEXT,
  refused_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- Row Level Security (RLS) Policies
-- ==============================================================================

ALTER TABLE public.registration_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refused_members ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_club_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY INVOKER SET search_path = ''
AS $$ SELECT coalesce((auth.jwt() -> 'app_metadata' ->> 'club_admin') = 'true', false); $$;

-- 1. registration_settings: Public can read, authenticated or admin can update
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registration_settings' AND policyname = 'Public can view registration_settings') THEN
    CREATE POLICY "Public can view registration_settings" ON public.registration_settings FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registration_settings' AND policyname = 'Allow modification of registration_settings') THEN
    CREATE POLICY "Allow modification of registration_settings" ON public.registration_settings FOR ALL USING (true);
  END IF;
END $$;

-- 2. registrations: Public can INSERT only when is_open = true and status = 'pending'.
-- Public cannot SELECT from registrations. Admins can SELECT, UPDATE, DELETE.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registrations' AND policyname = 'Public can insert registrations when open') THEN
    CREATE POLICY "Public can insert registrations when open" ON public.registrations
    FOR INSERT WITH CHECK (
      status = 'pending' AND refusal_reason IS NULL AND
      EXISTS (
        SELECT 1 FROM public.registration_settings
        WHERE is_open = true AND active_season = registration_season
      )
    );
  END IF;
  EXECUTE 'DROP POLICY IF EXISTS "Full access to registrations" ON public.registrations';
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registrations' AND policyname = 'Officer can read registrations') THEN
    CREATE POLICY "Officer can read registrations" ON public.registrations FOR SELECT TO authenticated USING (public.is_club_admin());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'registrations' AND policyname = 'Officer can decide registrations') THEN
    CREATE POLICY "Officer can decide registrations" ON public.registrations FOR UPDATE TO authenticated
    USING (public.is_club_admin() AND status = 'pending')
    WITH CHECK (public.is_club_admin() AND status IN ('accepted', 'refused'));
  END IF;
END $$;

-- 3. members: Public can view accepted club members
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'members' AND policyname = 'Public can view members') THEN
    CREATE POLICY "Public can view members" ON public.members FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'members' AND policyname = 'Full access to members') THEN
    CREATE POLICY "Full access to members" ON public.members FOR ALL USING (true);
  END IF;
END $$;

-- 4. refused_members: Private table
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'refused_members' AND policyname = 'Full access to refused_members') THEN
    CREATE POLICY "Full access to refused_members" ON public.refused_members FOR ALL USING (true);
  END IF;
END $$;

-- ==============================================================================
-- Atomic Stored Procedures for Acceptance, Refusal, and Season Closing
-- ==============================================================================

-- Decisions update the application in place so registrations remains the only history.
DROP FUNCTION IF EXISTS public.accept_club_registration(bigint);
DROP FUNCTION IF EXISTS public.refuse_club_registration(bigint,text);
CREATE OR REPLACE FUNCTION public.decide_club_registration(p_registration_id bigint, p_decision text, p_reason text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
DECLARE registration_record public.registrations%ROWTYPE;
BEGIN
  IF NOT public.is_club_admin() THEN RAISE EXCEPTION 'Officer access required'; END IF;
  IF p_decision NOT IN ('accepted', 'refused') THEN RAISE EXCEPTION 'Invalid decision'; END IF;
  IF p_decision = 'refused' AND (coalesce(length(trim(p_reason)), 0) = 0 OR length(p_reason) > 2000) THEN
    RAISE EXCEPTION 'Enter a refusal reason (up to 2000 characters)';
  END IF;
  UPDATE public.registrations
  SET status = p_decision,
      refusal_reason = CASE WHEN p_decision = 'refused' THEN trim(p_reason) ELSE NULL END
  WHERE id = p_registration_id AND status = 'pending'
  RETURNING * INTO registration_record;
  IF NOT FOUND THEN RAISE EXCEPTION 'Application already processed or no longer exists'; END IF;
  RETURN jsonb_build_object('registration_id', registration_record.id, 'decision', p_decision);
END; $$;
REVOKE EXECUTE ON FUNCTION public.decide_club_registration(bigint,text,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.decide_club_registration(bigint,text,text) TO authenticated;

-- Safe Season Closing: checks if pending registrations exist before closing
CREATE OR REPLACE FUNCTION public.close_registration_season()
RETURNS public.registration_settings
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_pending_count INT;
  v_settings public.registration_settings%ROWTYPE;
BEGIN
  -- 1. Check for pending applications
  SELECT COUNT(*) INTO v_pending_count FROM public.registrations WHERE status = 'pending';
  IF v_pending_count > 0 THEN
    RAISE EXCEPTION 'Cannot close registration: % pending application(s) exist. Please accept or refuse all applications before closing.', v_pending_count;
  END IF;

  -- 2. Close registration
  UPDATE public.registration_settings
  SET
    is_open = false,
    closed_at = NOW(),
    updated_at = NOW()
  WHERE id = 1
  RETURNING * INTO v_settings;

  RETURN v_settings;
END;
$$;
