import { useEffect, useMemo, useRef, useState } from "react";
import Footer from "../Footer/Footer";
import { NAV_GALLERY_COLUMN_ONE, NAV_GALLERY_COLUMN_TWO } from "../FullNavMenu/navigationGallery";
import { readPublicForm, submitPublicForm, validatePublicAnswers } from "../../lib/dynamicForms";
import { publicContent } from "../../lib/supabaseClient";
import "../RegistrationPage/RegistrationPage.css";
import "./DynamicFormPage.css";

function DynamicField({ field, value, error, onChange }) {
  const props = { id: `dynamic-${field.id}`, name: field.id, value: value || "", required: field.required, "aria-invalid": Boolean(error), "aria-describedby": error ? `dynamic-${field.id}-error` : field.description ? `dynamic-${field.id}-help` : undefined, onChange: (event) => onChange(event.target.value) };
  let control;
  if (field.field_type === "long_text") control = <textarea {...props} rows="4" maxLength="4000" placeholder={field.placeholder} />;
  else if (field.field_type === "select") control = <select {...props}><option value="">Choose an option</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select>;
  else if (field.field_type === "radio" || field.field_type === "checkboxes") control = <fieldset id={props.id} tabIndex="-1" className="dynamic-choice-list"><legend className="reg-sr-only">{field.label}</legend>{field.options.map((option) => { const checked = field.field_type === "checkboxes" ? (value || []).includes(option) : value === option; return <label key={option}><input type={field.field_type === "checkboxes" ? "checkbox" : "radio"} name={field.id} checked={checked} onChange={() => field.field_type === "checkboxes" ? onChange(checked ? value.filter((item) => item !== option) : [...(value || []), option]) : onChange(option)} /><span>{option}</span></label>; })}</fieldset>;
  else control = <input {...props} type={{ email: "email", phone: "tel", number: "number", date: "date" }[field.field_type] || "text"} maxLength={field.field_type === "short_text" ? 500 : undefined} placeholder={field.placeholder} />;
  return <div className="reg-field reg-field-wide dynamic-public-field"><label htmlFor={field.field_type === "radio" || field.field_type === "checkboxes" ? undefined : props.id}>{field.label}{!field.required && <span> (optional)</span>}</label>{field.description && <p id={`dynamic-${field.id}-help`}>{field.description}</p>}{control}{error && <span className="reg-field-error" id={`dynamic-${field.id}-error`}>{error}</span>}</div>;
}

export default function DynamicFormPage({ slug, onBack, onOpenAdmin, onNavigateRegister }) {
  const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [values, setValues] = useState({}); const [errors, setErrors] = useState({}); const [submitting, setSubmitting] = useState(false); const [success, setSuccess] = useState(false);
  const successRef = useRef(null);
  useEffect(() => { let active = true; setLoading(true); readPublicForm(publicContent, slug).then((data) => { if (!active) return; setForm(data); setValues(Object.fromEntries((data?.form_fields || []).map((field) => [field.id, field.field_type === "checkboxes" ? [] : ""]))); }).catch((error) => active && setLoadError(error.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [slug]);
  const fields = useMemo(() => form?.form_fields || [], [form]);
  const submit = async (event) => { event.preventDefault(); if (submitting) return; setLoadError(""); const nextErrors = validatePublicAnswers(fields, values); setErrors(nextErrors); if (Object.keys(nextErrors).length) { document.getElementById(`dynamic-${Object.keys(nextErrors)[0]}`)?.focus(); return; } setSubmitting(true); try { const result = await submitPublicForm(publicContent, slug, fields, values); if (Object.keys(result.errors).length) { setErrors(result.errors); return; } setSuccess(true); requestAnimationFrame(() => successRef.current?.focus()); } catch (error) { setLoadError(error.message); } finally { setSubmitting(false); } };
  return <div className="reg-nav-overlay is-visible dynamic-form-page"><div className="reg-nav-topography" aria-hidden="true"><svg viewBox="0 0 1440 900" fill="none" preserveAspectRatio="xMidYMid slice"><path d="M-100 200 C 200 150 400 350 700 250 C1000 150 1200 400 1600 300" stroke="rgba(37,99,235,.12)" strokeWidth="1.5"/><path d="M-50 450 C300 380 500 600 850 480 C1150 360 1350 640 1700 550" stroke="rgba(15,23,42,.07)" strokeWidth="1.5"/></svg></div>
    <header className="reg-nav-header-bar"><a href="/" onClick={(event) => { event.preventDefault(); onBack(); }} className="nav-brand-link" aria-label="RAI Robotics home"><img src="/RAI/club-icon-light.png" alt="RAI Robotics Logo" height="70" className="nav-brand-logo" /></a><button type="button" className="reg-btn-header-close" onClick={onBack} aria-label="Return to website"><span className="dash-bar close-bar-1"/><span className="dash-bar close-bar-2"/></button></header>
    <main className="reg-nav-body"><div className="reg-nav-left-content">
      <section className="dynamic-form-shell">
        {loading ? <div className="dynamic-form-message" role="status">Loading form…</div> : !form ? <div className="dynamic-form-message"><h1>Form unavailable</h1><p>{loadError || "This form does not exist, is still a draft, or is no longer accepting responses."}</p><button type="button" className="reg-submit" onClick={onBack}>Return to website</button></div> : success ? <div className="reg-success" ref={successRef} tabIndex="-1" role="status"><span className="reg-success-icon" aria-hidden="true">✓</span><h2>Response received.</h2><p>{form.success_message}</p><button className="dynamic-submit-another" type="button" onClick={() => { setSuccess(false); setValues(Object.fromEntries(fields.map((field) => [field.id, field.field_type === "checkboxes" ? [] : ""]))); }}>Submit another response</button></div> : <><div className="dynamic-form-intro"><span>Robotics &amp; AI Club · EST Safi</span><h1>{form.title}</h1>{form.description && <p>{form.description}</p>}</div><form className="reg-form dynamic-public-form" onSubmit={submit} noValidate aria-busy={submitting}><p className="reg-form-hint">Fields marked optional may be left empty.</p><div className="reg-form-grid">{fields.map((field) => <DynamicField key={field.id} field={field} value={values[field.id]} error={errors[field.id]} onChange={(value) => { setValues((current) => ({ ...current, [field.id]: value })); setErrors((current) => ({ ...current, [field.id]: "" })); }} />)}</div><button className="reg-submit" type="submit" disabled={submitting}><span>{submitting ? "Submitting…" : form.submit_button_label}</span><span aria-hidden="true">↗</span></button>{loadError && <p className="reg-notice reg-submit-error" role="alert">{loadError}</p>}</form></>}
      </section>
    </div><div className="reg-nav-right-gallery"><div className="reg-nav-infinite-columns">{[[...NAV_GALLERY_COLUMN_ONE,...NAV_GALLERY_COLUMN_ONE],[...NAV_GALLERY_COLUMN_TWO,...NAV_GALLERY_COLUMN_TWO]].map((images,column) => <div className={`infinite-col ${column ? "col-down" : "col-up"}`} key={column}><div className="infinite-col-track">{images.map((image,index) => <div className="reg-nav-img-card" key={`${image.src}-${index}`}><div className="reg-nav-img-wrapper"><img src={image.src} alt={image.alt} loading="lazy" /></div></div>)}</div></div>)}</div></div></main>
    <Footer onOpenAdmin={onOpenAdmin} onNavigateRegister={onNavigateRegister} />
  </div>;
}
